### ISSUE TITLE
Improvement proposal.

### ISSUE THREAD

**Issue by Escape142** [SamirMoustafa/torch-operation-counter#3]
Including information about the differences between FLOPS and OPS in the README would be highly beneficial. Additionally, outlining the advantages of this library over alternatives like THOP would be valuable for users to understand its unique benefits.

**Comment by SamirMoustafa** [comment]
@Escape142 Thanks for highlighting the need to clarify FLOPS (Floating Point per Second) and OPS (Operations) in the README, and the advantages of our library over `THOP`. 
I'm open to additional ideas and would appreciate a pull request to have these improvements.

**Comment by Freed-Wu** [comment]
Compared from pytorch official FlopCounterMode(), what is the improvement about this project?

https://github.com/pytorch/pytorch/issues/5013#issuecomment-2372032531
